"""Storage boundary: domain operations contain no SQL."""
from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol


class Storage(Protocol):
    def transaction(self) -> AbstractContextManager: ...
    def savepoint(self) -> AbstractContextManager: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def put_thumbnail(self, photo: dict, data: bytes) -> None: ...
    def create_album(self, name: str) -> dict: ...
    def change_members(self, album_id: str, photo_ids: list[str], *, remove: bool = False) -> dict: ...
    def photo(self, photo_id: str) -> dict: ...
    def default_index_profile(self) -> str | None: ...
    def index_profile(self, profile_id: str) -> dict: ...
    def library(self, root_path: str, root_key: str) -> dict: ...
    def photos_for_library(self, library_id: str) -> list[dict]: ...
    def put_photo(self, photo: dict) -> None: ...
    def start_scan(self, scan_id: str, library_id: str) -> None: ...
    def event(self, scan_id: str, kind: str, photo_id: str | None, path: str, error: dict | None = None) -> None: ...
    def finish_scan(self, scan_id: str, result: dict) -> None: ...


class IndexStorage(Protocol):
    def transaction(self) -> AbstractContextManager: ...
    def read_snapshot(self) -> AbstractContextManager: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def photo(self, photo_id: str) -> dict: ...
    def put_index_profile(self, profile: dict) -> str: ...
    def index_profile(self, profile_id: str) -> dict: ...
    def index_profiles(self) -> list[dict]: ...
    def default_index_profile(self) -> str | None: ...
    def set_default_index_profile(self, profile_id: str) -> None: ...
    def index_photos(self, *, album_id: str | None = None, library_id: str | None = None) -> list[dict]: ...
