"""Storage boundary: domain operations contain no SQL."""
from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol


class Storage(Protocol):
    database_path: Path
    writable: bool

    def assert_writable(self) -> None: ...
    def transaction(self) -> AbstractContextManager: ...
    def savepoint(self) -> AbstractContextManager: ...
    def read_snapshot(self) -> AbstractContextManager: ...
    def album(self) -> dict: ...
    def backup(self, output: Path | str) -> dict: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def put_thumbnail(self, photo: dict, data: bytes) -> None: ...
    def photo(self, photo_id: str) -> dict: ...
    def photos(self) -> list[dict]: ...
    def folder(self, folder_id: str) -> dict: ...
    def folders(self) -> list[dict]: ...
    def folder_by_name_key(self, key: str) -> dict | None: ...
    def photo_folders(self, photo_id: str) -> list[dict]: ...
    def photos_in_folders(self, folder_ids: list[str], match: str) -> list[dict]: ...
    def _create_folder(self, folder: dict) -> None: ...
    def _rename_folder(self, folder_id: str, name: str, name_key: str) -> None: ...
    def _delete_folder(self, folder_id: str) -> None: ...
    def _add_folder_photos(self, folder_id: str, photo_ids: list[str]) -> int: ...
    def _remove_folder_photos(self, folder_id: str, photo_ids: list[str]) -> int: ...
    def put_photo(self, photo: dict) -> None: ...
    def default_embedding_profile(self) -> str | None: ...
    def embedding_profile(self, profile_id: str) -> dict: ...
    def start_scan(self, scan_id: str, source_absolute_path: str,
                   source_relative_path: str | None = None) -> None: ...
    def event(self, scan_id: str, kind: str, photo_id: str | None, path: str,
              error: dict | None = None) -> None: ...
    def finish_scan(self, scan_id: str, result: dict) -> None: ...
    def scan(self, scan_id: str) -> dict: ...
    def events(self, scan_id: str, limit: int = 100, after: int = 0,
               changes_only: bool = False) -> dict: ...


class ImageEmbeddingStorage(Protocol):
    def assert_writable(self) -> None: ...
    def transaction(self) -> AbstractContextManager: ...
    def read_snapshot(self) -> AbstractContextManager: ...
    def album(self) -> dict: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def photo(self, photo_id: str) -> dict: ...
    def photos(self) -> list[dict]: ...
    def put_embedding_profile(self, profile: dict) -> str: ...
    def embedding_profile(self, profile_id: str) -> dict: ...
    def embedding_profiles(self) -> list[dict]: ...
    def default_embedding_profile(self) -> str | None: ...
    def set_default_embedding_profile(self, profile_id: str) -> None: ...


class ImageFeatureStorage(Protocol):
    def put_feature_profile(self, profile: dict) -> str: ...
    def feature_profile(self, profile_id: str) -> dict: ...
    def feature_profiles(self, component: str | None = None) -> list[dict]: ...
    def default_feature_profile(self, component: str) -> str | None: ...
    def set_default_feature_profile(self, component: str, profile_id: str) -> None: ...
    def put_feature_result(self, photo_id: str, profile_id: str, input_manifest: dict, payload: dict, *,
                           feature_dependencies=(), embedding_dependencies=()) -> str: ...
    def feature_result(self, result_id: str) -> dict: ...
    def find_feature_result(self, photo_id: str, profile_id: str, input_fingerprint: str) -> dict | None: ...
    def has_feature_results(self, photo_id: str, profile_id: str) -> bool: ...
    def feature_history(self, photo_id: str, profile_id: str, *, limit: int = 100, after: str = "") -> list[dict]: ...
    def put_scene_prototypes(self, profile_id: str, prototypes: list[dict]) -> str: ...
    def scene_prototype_set(self, profile_id: str) -> dict | None: ...
    def create_feature_run(self, plan: dict) -> None: ...
    def feature_run(self, run_id: str) -> dict: ...
    def feature_items(self, run_id: str) -> list[dict]: ...
    def update_feature_run(self, run_id: str, **changes) -> None: ...
    def update_feature_item(self, run_id: str, item: dict) -> None: ...
    def claim_feature_input(self, run_id: str, item_id: str, profile_id: str, input_fingerprint: str) -> None: ...
    def release_feature_input(self, run_id: str, item_id: str) -> None: ...
    def put_similarity_pairs(self, run_id: str, pairs: list[dict]) -> None: ...
    def similarity_pairs(self, run_id: str, *, limit: int = 100, after: int = 0) -> dict: ...
    def rebuild_feature_fts(self) -> dict: ...
    def validate_feature_schema(self) -> None: ...
