"""Storage boundary: domain operations contain no SQL."""
from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol


class Storage(Protocol):
    def transaction(self) -> AbstractContextManager: ...
    def savepoint(self) -> AbstractContextManager: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def put_thumbnail(self, photo: dict, data: bytes) -> None: ...
    def create_album(self, name: str) -> dict: ...
    def change_members(self, album_id: str, photo_ids: list[str], *, remove: bool = False) -> dict: ...
    def photo(self, photo_id: str) -> dict: ...
    def analysis_records(self, photo_id: str) -> list[dict]: ...
    def latest_analysis_failure(self, photo_id: str) -> dict | None: ...
    def library(self, root_path: str, root_key: str) -> dict: ...
    def photos_for_library(self, library_id: str) -> list[dict]: ...
    def put_photo(self, photo: dict) -> None: ...
    def start_scan(self, scan_id: str, library_id: str) -> None: ...
    def event(self, scan_id: str, kind: str, photo_id: str | None, path: str, error: dict | None = None) -> None: ...
    def finish_scan(self, scan_id: str, result: dict) -> None: ...


class AnalysisStorage(Protocol):
    def transaction(self) -> AbstractContextManager: ...
    def thumbnail(self, photo_id: str, *, include_data: bool = True) -> dict: ...
    def photo(self, photo_id: str) -> dict: ...
    def put_photo(self, photo: dict) -> None: ...
    def cached_analysis(self, photo_id: str, cache_key: str) -> dict | None: ...
    def put_analysis(self, record: dict) -> None: ...
    def save_analysis_run(self, result: dict) -> None: ...


class EmbeddingStorage(Protocol):
    def transaction(self) -> AbstractContextManager: ...
    def read_snapshot(self) -> AbstractContextManager: ...
    def photo(self, photo_id: str) -> dict: ...
    def search_photos(self, *, album_id=None, library_id=None) -> list[dict]: ...
    def embedding_candidates(self, encoder_id: str, *, album_id=None, library_id=None) -> dict: ...
    def embedding(self, photo_id: str, encoder_id: str) -> dict | None: ...
    def encoder(self, encoder_id: str) -> dict | None: ...
    def put_embedding(self, record: dict, profile: dict) -> None: ...
